import type { Task } from "@/types/interfaces/task"
import { MOCK_CATEGORIES } from "./categories"

export const MOCK_TASKS: Task[] = [
  {
    id: "1",
    user_id: "u1",
    title: "Prepare Monthly Report",
    description: "Compile data from Q3 analytics and create presentation slides.",
    due_date: new Date().toISOString(),
    start_time: "13:00",
    due_time: "14:00",
    status: "pending",
    priority: "high",
    category_id: "c1",
    category: MOCK_CATEGORIES[0],
    is_recurring: false,
    created_at: "", updated_at: "", start_date: null, all_day: false, recurrence_rule: null, parent_task_id: null, completed_at: null, deleted_at: null,
  },
  {
    id: "2",
    user_id: "u1",
    title: "Grocery Shopping",
    description: "Buy vegetables, fruits, and weekly groceries",
    due_date: new Date(Date.now() + 86400000).toISOString(),
    start_time: "09:00",
    due_time: "10:00",
    status: "pending",
    priority: "medium",
    category_id: "c3",
    category: MOCK_CATEGORIES[2],
    is_recurring: false,
    created_at: "", updated_at: "", start_date: null, all_day: false, recurrence_rule: null, parent_task_id: null, completed_at: null, deleted_at: null,
  },
  {
    id: "3",
    user_id: "u1",
    title: "Client Meeting",
    description: "Discuss project roadmap and timeline",
    due_date: new Date().toISOString(),
    start_time: "11:00",
    due_time: "13:00",
    status: "completed",
    priority: "urgent",
    category_id: "c1",
    category: MOCK_CATEGORIES[0],
    is_recurring: false,
    created_at: "", updated_at: "", start_date: null, all_day: false, recurrence_rule: null, parent_task_id: null, completed_at: null, deleted_at: null,
  },
  {
    id: "4",
    user_id: "u1",
    title: "Morning Jog",
    description: "30 minute run in the park",
    due_date: new Date().toISOString(),
    start_time: "06:30",
    due_time: "07:00",
    status: "pending",
    priority: "low",
    category_id: "c2",
    category: MOCK_CATEGORIES[1],
    is_recurring: true,
    created_at: "", updated_at: "", start_date: null, all_day: false, recurrence_rule: null, parent_task_id: null, completed_at: null, deleted_at: null,
  },
  {
    id: "5",
    user_id: "u1",
    title: "Developing API Integration",
    description: "Working on connecting to the payment gateway API",
    due_date: new Date().toISOString(),
    start_time: "14:00",
    due_time: "16:00",
    status: "in-progress",
    priority: "high",
    category_id: "c1",
    category: MOCK_CATEGORIES[0],
    is_recurring: false,
    created_at: "", updated_at: "", start_date: null, all_day: false, recurrence_rule: null, parent_task_id: null, completed_at: null, deleted_at: null,
  },
  {
    id: "6",
    user_id: "u1",
    title: "UI Design Review",
    description: "Review the new dashboard designs with the team",
    due_date: new Date().toISOString(),
    start_time: "16:00",
    due_time: "17:00",
    status: "pending",
    priority: "medium",
    category_id: "c1",
    category: MOCK_CATEGORIES[0],
    is_recurring: false,
    created_at: "", updated_at: "", start_date: null, all_day: false, recurrence_rule: null, parent_task_id: null, completed_at: null, deleted_at: null,
  }
]

export async function getTasks(): Promise<Task[]> {
  // Simulate DB call
  return MOCK_TASKS
}
