create table public.teams (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  deleted_at timestamp with time zone null,
  name text null,
  description text null,
  owner_id uuid null,
  avatar_url text null,
  cover_url text null,
  brand_color text null,
  is_active boolean null default true,
  last_updated_by uuid null,
  constraint teams_pkey primary key (id),
  constraint teams_last_updated_by_fkey foreign KEY (last_updated_by) references auth.users (id) on delete set null,
  constraint teams_owner_id_fkey foreign KEY (owner_id) references users (id)
) TABLESPACE pg_default;

create trigger trg_team_audit_process BEFORE INSERT
or
update on teams for EACH row
execute FUNCTION handle_team_audit ();

create table public.team_members (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  deleted_at timestamp with time zone null,
  team_id uuid null,
  user_id uuid null,
  role text null default 'MEMBER'::text,
  status text null default 'PENDING'::text,
  invited_at timestamp with time zone null default now(),
  joined_at timestamp with time zone null,
  constraint team_members_pkey primary key (id),
  constraint unique_team_membership unique (team_id, user_id),
  constraint team_members_team_id_fkey foreign KEY (team_id) references teams (id) on delete CASCADE,
  constraint team_members_user_id_fkey foreign KEY (user_id) references users (id),
  constraint check_team_role check (
    (role = any (array['ADMIN'::text, 'MEMBER'::text]))
  ),
  constraint check_team_status check (
    (
      status = any (
        array[
          'PENDING'::text,
          'ACCEPTED'::text,
          'DECLINED'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.team_logs (
  id uuid not null default gen_random_uuid (),
  team_id uuid not null,
  user_id uuid null,
  action_type text not null,
  old_data jsonb null,
  new_data jsonb null,
  created_at timestamp with time zone null default now(),
  constraint team_logs_pkey primary key (id),
  constraint team_logs_team_id_fkey foreign KEY (team_id) references teams (id) on delete CASCADE,
  constraint team_logs_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_team_logs_team_id on public.team_logs using btree (team_id) TABLESPACE pg_default;
